version: '3.7'
services:
  aktin-broker:
    image: ghcr.io/aktin/aktin-broker:1.3.4
    environment:
      LOG_LEVEL: ${AKTIN_BROKER_LOG_LEVEL:-INFO}
      PASSWORD: ${AKTIN_ADMIN_PW:-changeme}
      HOST_AND_PORT: ${AKTIN_BROKER_HOST_AND_PORT:-127.0.0.0:8080}
    volumes:
    - ./api-keys.properties:/opt/aktin/api-keys.properties
    ports:
    - ${AKTIN_BROKER_PORT:-127.0.0.1:8082}:8080
