version: '3.7'
services:
  aktin-broker:
    image: harbor.miracum.org/codex-ap2/aktin-broker:1.1.2-snapshot
    environment:
      PASSWORD: ${AKTIN_ADMIN_PW:-changeme}
      HOST_AND_PORT: ${AKTIN_BROKER_HOST_AND_PORT:-0.0.0.0:8080}
    volumes:
    - ./api-keys.properties:/opt/codex-aktin/api-keys.properties
    ports:
    - ${AKTIN_BROKER_PORT:-127.0.0.1:8082}:8080
