version: '3.7'
services:
  aktin-client:
    image: ghcr.io/medizininformatik-initiative/feasibility-aktin-client:1.4.0
    environment:
      BROKER_REQUEST_MEDIATYPE: ${FEASIBILITY_AKTIN_CLIENT_BROKER_REQUEST_MEDIATYPE:-application/sq+json}
      BROKER_RESULT_MEDIATYPE: ${FEASIBILITY_AKTIN_CLIENT_BROKER_RESULT_MEDIATYPE:-application/json}
      BROKER_ENDPOINT_URI: ${FEASIBILITY_AKTIN_CLIENT_BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${FEASIBILITY_AKTIN_CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${FEASIBILITY_AKTIN_CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_PING_SECONDS: ${FEASIBILITY_AKTIN_CLIENT_WEBSOCKET_PING_SECONDS:-60}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${FEASIBILITY_AKTIN_CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${FEASIBILITY_AKTIN_CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${FEASIBILITY_AKTIN_CLIENT_PROCESS_TIMEOUT_SECONDS:-60}
      CLIENT_OBFUSCATE: ${FEASIBILITY_AKTIN_CLIENT_OBFUSCATE:-true}
      JAVA_OPTS: ${FEASIBILITY_AKTIN_JAVA_OPTS}
      PROCESS_EXECUTOR_THREADS: ${FEASIBILITY_AKTIN_PROCESS_EXECUTOR_THREADS:-1}
      CQL_FHIR_BASE_URL: ${FEASIBILITY_AKTIN_CQL_FHIR_BASE_URL}
      CQL_FHIR_USER: ${FEASIBILITY_AKTIN_CQL_FHIR_USER}
      CQL_FHIR_PW: ${FEASIBILITY_AKTIN_CQL_FHIR_PW}
      FLARE_URL: ${FEASIBILITY_AKTIN_FLARE_URL:-http://flare:8080/query/execute}
      FLARE_USER: ${FEASIBILITY_AKTIN_FLARE_USER}
      FLARE_PW: ${FEASIBILITY_AKTIN_FLARE_PW}
      LOG_LEVEL: ${FEASIBILITY_AKTIN_LOG_LEVEL:-INFO}
      LOG_LEVEL_FEASIBILITY: ${FEASIBILITY_AKTIN_LOG_LEVEL_FEASIBILITY:-FINE}
